[package]
name = "zj-quit"
version = "0.3.0"
authors = ["Cristian Dominguez"]
edition = "2018"

[dependencies]
zellij-tile = "0.41.0"

[patch.crates-io]
zellij-tile = { git = "https://github.com/zellij-org/zellij", package = "zellij-tile" }
